name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - main # master 分支有 push 行为时就触发这个 action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.HEXO_DEPLOY }}
          PUBLISH_REPOSITORY: Jas0n0ss/Jas0n0ss.github.io
          BRANCH: master # 分支，填 gh-pages 就行
          PUBLISH_DIR: / # 部署 public 目录下的文件

